name: finance_ui
description: Finance Ui
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  device_preview: ^1.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  generate: true
  
